<x-layouts.app title="Provider dashboard">
    <div class="grid gap-6">
        <div><p class="font-bold uppercase tracking-widest text-navy-800">Service Provider</p><h1 class="text-3xl font-black">Provider dashboard</h1></div>
        @if(!$profile)
            <div class="rounded-2xl bg-white p-6 shadow-sm"><p>Complete your provider profile to appear in service searches.</p><a class="mt-4 inline-block rounded-lg bg-navy-900 px-5 py-3 font-bold text-white" href="{{ route('provider.profiles.create') }}">Create provider profile</a></div>
        @else
            <div class="grid gap-4 md:grid-cols-3"><div class="rounded-2xl border-t-4 border-gold-400 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Availability</p><p class="text-xl font-bold">{{ $profile->available_now ? 'Available now' : 'Unavailable' }}</p></div><div class="rounded-2xl border-t-4 border-navy-800 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Service area</p><p class="text-xl font-bold">{{ $profile->municipality->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $profile->province->name }}@if($profile->service_radius_km) · {{ $profile->service_radius_km }} km radius @endif</p></div><div class="rounded-2xl border-t-4 border-sky-500 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Services</p><p class="text-xl font-bold">{{ $profile->providerServices->count() }}</p>@if(auth()->user()->isIdentityVerified())<p class="mt-2 inline-flex rounded-full bg-gold-100 px-3 py-1 text-sm font-bold text-navy-900">Identity verified</p>@else<p class="mt-1 text-sm text-slate-500">Verification: {{ str($profile->verification_status->value)->headline() }}</p>@endif</div></div>
            @if($profile->bio)<div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="font-bold">About my work</h2><p class="mt-2 text-slate-600">{{ $profile->bio }}</p></div>@endif
            <div class="grid gap-4 md:grid-cols-2"><div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="font-bold">Services offered</h2><ul class="mt-3 grid gap-2">@foreach($profile->providerServices as $providerService)<li class="rounded-lg bg-slate-50 px-3 py-2">{{ $providerService->service->name }}</li>@endforeach</ul></div><div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="font-bold">Credential summary</h2>@forelse($profile->credentials_metadata ?? [] as $credential)<p class="mt-3 rounded-lg bg-slate-50 px-3 py-2">{{ $credential }}</p>@empty<p class="mt-3 text-slate-500">No credentials added yet.</p>@endforelse</div></div>
            <div class="flex flex-wrap gap-3"><form method="POST" action="{{ route('provider.availability.update', $profile) }}">@csrf @method('PATCH')<input type="hidden" name="available_now" value="{{ $profile->available_now ? 0 : 1 }}"><button class="rounded-lg bg-navy-900 px-5 py-3 font-bold text-white">{{ $profile->available_now ? 'Go unavailable' : 'Go available' }}</button></form><a class="rounded-lg border border-slate-300 px-5 py-3 font-bold" href="{{ route('provider.profiles.edit', $profile) }}">Edit profile</a></div>
        @endif
    </div>
</x-layouts.app>
