<?php

use App\Http\Controllers\Admin\AccountTypeController;
use App\Http\Controllers\Admin\AuditLogController;
use App\Http\Controllers\Admin\CommissionController as AdminCommissionController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\DisputeController as AdminDisputeController;
use App\Http\Controllers\Admin\EnforcementCaseController as AdminEnforcementCaseController;
use App\Http\Controllers\Admin\FinanceReportController;
use App\Http\Controllers\Admin\JobController as AdminJobController;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\ProviderController as AdminProviderController;
use App\Http\Controllers\Admin\ReportController as AdminReportController;
use App\Http\Controllers\Admin\ResolvedEnforcementCaseController;
use App\Http\Controllers\Admin\ReviewedEnforcementAppealController;
use App\Http\Controllers\Admin\ServiceCatalogController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\VerificationReviewController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\Auth\SendEmailVerificationController;
use App\Http\Controllers\Auth\VerifyEmailController;
use App\Http\Controllers\CancelledServiceRequestController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DisputeController;
use App\Http\Controllers\EnforcementAppealController;
use App\Http\Controllers\EnforcementCaseController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\JobMessageController;
use App\Http\Controllers\JobPaymentController;
use App\Http\Controllers\JobStatusController;
use App\Http\Controllers\MessagesController;
use App\Http\Controllers\MobileVerificationController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\Provider\AcceptedServiceRequestController;
use App\Http\Controllers\Provider\AvailabilityController;
use App\Http\Controllers\Provider\DeclinedServiceRequestController;
use App\Http\Controllers\Provider\ProfileController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\ProviderSearchController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\ServiceRequestController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\Staff\JobPaymentReleaseController;
use App\Http\Controllers\Staff\WithdrawalReviewController;
use App\Http\Controllers\UserReportController;
use App\Http\Controllers\VerificationController;
use App\Http\Controllers\WalletController;
use App\Http\Controllers\WithdrawalController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/find-help', ProviderSearchController::class)->name('providers.search');
Route::get('/providers/{provider_profile}', ProviderController::class)->name('providers.show');
Route::get('/locations/{province}/municipalities', [LocationController::class, 'municipalities'])->name('locations.municipalities');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:6,1');
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);
    Route::get('/forgot-password', [PasswordResetController::class, 'request'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'email'])->name('password.email')->middleware('throttle:6,1');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'reset'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'update'])->name('password.update');
});
Route::middleware(['auth', 'account.active'])->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/messages', [MessagesController::class, 'index'])->name('messages.index');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::patch('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::patch('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::post('/logout', LogoutController::class)->name('logout');
    Route::get('/admin/catalog', [ServiceCatalogController::class, 'index'])->name('admin.catalog');
    Route::get('/admin', AdminDashboardController::class)->name('admin.dashboard');
    Route::get('/admin/users', [AdminUserController::class, 'index'])->name('admin.users.index');
    Route::get('/admin/providers', [AdminProviderController::class, 'index'])->name('admin.providers.index');
    Route::get('/admin/jobs', [AdminJobController::class, 'index'])->name('admin.jobs.index');
    Route::get('/admin/reports', [AdminReportController::class, 'index'])->name('admin.reports.index');
    Route::get('/admin/audit-logs', [AuditLogController::class, 'index'])->name('admin.audit-logs.index');
    Route::post('/admin/categories', [ServiceCatalogController::class, 'storeCategory'])->name('admin.categories.store');
    Route::post('/admin/services', [ServiceCatalogController::class, 'storeService'])->name('admin.services.store');
    Route::post('/admin/locations', [LocationController::class, 'store'])->name('admin.locations.store');
    Route::get('/provider/dashboard', [ProfileController::class, 'index'])->name('provider.dashboard');
    Route::resource('/provider/profiles', ProfileController::class)->only(['create', 'store', 'edit', 'update'])->parameters(['profiles' => 'provider_profile'])->names('provider.profiles');
    Route::patch('/provider/profiles/{provider_profile}/availability', AvailabilityController::class)->name('provider.availability.update');
    Route::get('/verification', [VerificationController::class, 'index'])->name('verification.index');
    Route::post('/verification/documents', [VerificationController::class, 'store'])->middleware('throttle:5,1')->name('verification.documents.store');
    Route::get('/verification/documents/{provider_document}', [VerificationController::class, 'download'])->name('verification.documents.download');
    Route::get('/verification/email/verify/{id}/{hash}', VerifyEmailController::class)->middleware(['signed', 'throttle:6,1'])->name('verification.verify');
    Route::post('/verification/email/resend', SendEmailVerificationController::class)->middleware('throttle:6,1')->name('verification.send');
    Route::post('/verification/mobile', [MobileVerificationController::class, 'send'])->middleware('throttle:5,1')->name('verification.mobile.send');
    Route::post('/verification/mobile/confirm', [MobileVerificationController::class, 'verify'])->middleware('throttle:10,1')->name('verification.mobile.verify');
    Route::get('/admin/verifications', [VerificationReviewController::class, 'index'])->name('admin.verifications.index');
    Route::patch('/admin/verifications/{provider_document}', [VerificationReviewController::class, 'update'])->name('admin.verifications.update');
    Route::get('/service-requests', [ServiceRequestController::class, 'index'])->name('service-requests.index');
    Route::get('/providers/{provider_profile}/service-requests/create', [ServiceRequestController::class, 'create'])->name('service-requests.create');
    Route::post('/providers/{provider_profile}/service-requests', [ServiceRequestController::class, 'store'])->middleware('throttle:10,1')->name('service-requests.store');
    Route::get('/service-requests/{service_request}', [ServiceRequestController::class, 'show'])->name('service-requests.show');
    Route::patch('/service-requests/{service_request}/accept', AcceptedServiceRequestController::class)->name('service-requests.accept');
    Route::patch('/service-requests/{service_request}/decline', DeclinedServiceRequestController::class)->name('service-requests.decline');
    Route::patch('/service-requests/{service_request}/cancel', CancelledServiceRequestController::class)->name('service-requests.cancel');
    Route::get('/jobs', [JobController::class, 'index'])->name('jobs.index');
    Route::get('/jobs/{job}', [JobController::class, 'show'])->name('jobs.show');
    Route::patch('/jobs/{job}/status', JobStatusController::class)->name('jobs.status.update');
    Route::post('/jobs/{job}/messages', [JobMessageController::class, 'store'])->middleware('throttle:20,1')->name('jobs.messages.store');
    Route::post('/jobs/{job}/reports', [UserReportController::class, 'store'])->middleware('throttle:5,1')->name('jobs.reports.store');
    Route::post('/jobs/{job}/reviews', [ReviewController::class, 'store'])->middleware('throttle:5,1')->name('jobs.reviews.store');
    Route::post('/jobs/{job}/disputes', [DisputeController::class, 'store'])->middleware('throttle:5,1')->name('disputes.store');
    Route::patch('/disputes/{dispute}/withdraw', [DisputeController::class, 'withdraw'])->name('disputes.withdraw');
    Route::get('/admin/disputes', [AdminDisputeController::class, 'index'])->name('admin.disputes.index');
    Route::get('/admin/disputes/{dispute}', [AdminDisputeController::class, 'show'])->name('admin.disputes.show');
    Route::patch('/admin/disputes/{dispute}', [AdminDisputeController::class, 'update'])->name('admin.disputes.update');
    Route::patch('/job-payments/{job_payment}/confirm', [JobPaymentController::class, 'confirm'])->middleware('throttle:10,1')->name('job-payments.confirm');
    Route::get('/staff/job-payments', [JobPaymentReleaseController::class, 'index'])->name('staff.job-payments.index');
    Route::patch('/staff/job-payments/{job_payment}', [JobPaymentReleaseController::class, 'update'])->name('staff.job-payments.update');
    Route::get('/wallet', [WalletController::class, 'index'])->name('wallet.index');
    Route::get('/wallet/withdrawals', [WithdrawalController::class, 'index'])->name('withdrawals.index');
    Route::post('/wallet/withdrawals', [WithdrawalController::class, 'store'])->middleware('throttle:6,1')->name('withdrawals.store');
    Route::patch('/wallet/withdrawals/{withdrawal}/cancel', [WithdrawalController::class, 'cancel'])->name('withdrawals.cancel');
    Route::get('/sponsor/referrals', [SponsorController::class, 'index'])->name('sponsor.referrals');
    Route::get('/staff/withdrawals', [WithdrawalReviewController::class, 'index'])->name('staff.withdrawals.index');
    Route::patch('/staff/withdrawals/{withdrawal}', [WithdrawalReviewController::class, 'update'])->name('staff.withdrawals.update');
    Route::resource('/admin/account-types', AccountTypeController::class)->except(['show', 'destroy'])->parameters(['account-types' => 'account_type'])->names('admin.account-types');
    Route::patch('/admin/account-types/{account_type}/toggle', [AccountTypeController::class, 'toggle'])->name('admin.account-types.toggle');
    Route::get('/admin/commissions', [AdminCommissionController::class, 'index'])->name('admin.commissions.index');
    Route::patch('/admin/commissions/{commission}', [AdminCommissionController::class, 'update'])->name('admin.commissions.update');
    Route::get('/admin/finance', [FinanceReportController::class, 'index'])->name('admin.finance.index');
    Route::get('/admin/finance/ledger', [FinanceReportController::class, 'ledger'])->name('admin.finance.ledger');
    Route::get('/admin/finance/export', [FinanceReportController::class, 'export'])->name('admin.finance.export');
    Route::get('/admin/finance/users/{user}/statement', [FinanceReportController::class, 'userStatement'])->name('admin.finance.statement');
    Route::get('/enforcement-cases', [EnforcementCaseController::class, 'index'])->name('enforcement-cases.index');
    Route::get('/enforcement-cases/{enforcement_case}', [EnforcementCaseController::class, 'show'])->name('enforcement-cases.show');
    Route::post('/enforcement-cases/{enforcement_case}/appeal', EnforcementAppealController::class)->name('enforcement-cases.appeal');
    Route::get('/admin/enforcement', [AdminEnforcementCaseController::class, 'index'])->name('admin.enforcement.index');
    Route::get('/admin/enforcement/{enforcement_case}', [AdminEnforcementCaseController::class, 'show'])->name('admin.enforcement.show');
    Route::patch('/admin/enforcement/{enforcement_case}', [AdminEnforcementCaseController::class, 'update'])->name('admin.enforcement.update');
    Route::patch('/admin/enforcement/{enforcement_case}/resolve', ResolvedEnforcementCaseController::class)->name('admin.enforcement.resolve');
    Route::patch('/admin/enforcement/{enforcement_case}/appeal', ReviewedEnforcementAppealController::class)->name('admin.enforcement.appeal.update');
});
Route::get('/health', HealthController::class)->name('health');
