<x-layouts.admin title="Verification review queue">
    <div class="grid gap-6">
        <x-flash />
        <div><p class="font-bold uppercase tracking-widest text-navy-800">Administration</p><h1 class="text-3xl font-black">Verification review queue</h1><p class="mt-2 text-slate-600">Approval must be based on the private document. Automated submission never proves identity.</p></div>
        @forelse($documents as $document)
            <article class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-xl font-black">{{ $document->user->name }}</h2><p class="text-slate-600">{{ str($document->document_type->value)->headline() }} · submitted {{ $document->created_at->diffForHumans() }}</p></div><a class="rounded-lg border border-slate-300 px-4 py-2 font-bold" href="{{ route('verification.documents.download', $document) }}">Open private document</a></div><form class="mt-6 grid gap-4 md:grid-cols-2" method="POST" action="{{ route('admin.verifications.update', $document) }}">@csrf @method('PATCH')<label class="grid gap-2 font-semibold">Decision<select class="rounded-lg border border-slate-300 p-3" name="status" required><option value="VERIFIED">Verify</option><option value="REJECTED">Reject</option><option value="EXPIRED">Mark expired</option></select></label><label class="grid gap-2 font-semibold">Valid until (optional)<input class="rounded-lg border border-slate-300 p-3" type="date" name="expires_at" min="{{ now()->addDay()->toDateString() }}"></label><label class="grid gap-2 font-semibold md:col-span-2">Review notes<textarea class="rounded-lg border border-slate-300 p-3" name="notes" rows="3" placeholder="Required for rejection or expiration"></textarea></label><button class="justify-self-start rounded-lg bg-navy-900 px-5 py-3 font-bold text-white">Save review</button></form></article>
        @empty<div class="rounded-2xl bg-white p-8 text-center text-slate-500 shadow-sm">No verification submissions are waiting for review.</div>@endforelse
        {{ $documents->links() }}
    </div>
</x-layouts.admin>
